// Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

ced -i z:\TestData\configs\te_smsemsprt_commdb.cfg ced.log
copyfile z:\sms\tsmsemsprt_config.txt c:\sms\tsmsemsprt_config.txt
