// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\TestData\Scripts\TE_Fax_Setup_IR.script

LOAD_SUITE TE_Fax

START_TESTCASE TEL-FAX-NA-0001
//!@SYMTestCaseID TEL-FAX-NA-0001
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc
//!@SYMTestPriority critical
//!@SYMTestActions
//!@SYMTestExpectedResults Pass - If anthing fails the step will leave with error code 
//!@SYMTestType CT
RUN_TEST_STEP 120 TE_Fax TestFaxDefinition

END_TESTCASE TEL-FAX-NA-0001

START_TESTCASE TEL-FAX-NA-0002
//!@SYMTestCaseID TEL-FAX-NA-0002
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Initialises the test 
//!@SYMTestPriority critical
//!@SYMTestActions - Parses a config file to retreive phone numbers and initialises comms  
//!@SYMTestExpectedResults Pass - If anthing fails the step will leave with error code 
//!@SYMTestType CT
RUN_TEST_STEP 120 TE_Fax TestFaxStorage

END_TESTCASE TEL-FAX-NA-0002

START_TESTCASE TEL-FAX-NA-0003
//!@SYMTestCaseID TEL-FAX-NA-0003
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Initialises the test 
//!@SYMTestPriority critical
//!@SYMTestActions - Parses a config file to retreive phone numbers and initialises comms  
//!@SYMTestExpectedResults Pass - If anthing fails the step will leave with error code 
//!@SYMTestType CT
RUN_TEST_STEP 120 TE_Fax TestFaxCoding

END_TESTCASE TEL-FAX-NA-0003

START_TESTCASE TEL-FAX-NA-0004
//!@SYMTestCaseID TEL-FAX-NA-0004
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Initialises the test 
//!@SYMTestPriority critical
//!@SYMTestActions - Parses a config file to retreive phone numbers and initialises comms  
//!@SYMTestExpectedResults Pass - If anthing fails the step will leave with error code 
//!@SYMTestType CT
RUN_TEST_STEP 120 TE_Fax TestFaxHeaderDefinition

END_TESTCASE TEL-FAX-NA-0004

START_TESTCASE TEL-FAX-NA-0005
//!@SYMTestCaseID TEL-FAX-NA-0005
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 600 TE_Fax TestTransmitFax01
DELAY 5000


END_TESTCASE TEL-FAX-NA-0005

START_TESTCASE TEL-FAX-NA-0006
//!@SYMTestCaseID TEL-FAX-NA-0006
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 600 TE_Fax TestTransmitFax02
DELAY 5000


END_TESTCASE TEL-FAX-NA-0006

START_TESTCASE TEL-FAX-NA-0007
//!@SYMTestCaseID TEL-FAX-NA-0007
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 600 TE_Fax TestTransmitFax03
DELAY 5000


END_TESTCASE TEL-FAX-NA-0007

START_TESTCASE TEL-FAX-NA-0008
//!@SYMTestCaseID TEL-FAX-NA-0008
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 600 TE_Fax TestTransmitFax04
DELAY 5000


END_TESTCASE TEL-FAX-NA-0008

START_TESTCASE TEL-FAX-NA-0009
//!@SYMTestCaseID TEL-FAX-NA-0009
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT 
RUN_TEST_STEP 600 TE_Fax TestTransmitFax05
DELAY 5000


END_TESTCASE TEL-FAX-NA-0009

START_TESTCASE TEL-FAX-NA-0010
//!@SYMTestCaseID TEL-FAX-NA-0010
//!@SYMREQ REQ0000
//!@SYMTestCaseDesc Transmits a fax
//!@SYMTestPriority High
//!@SYMTestActions Transmits a fax using various settings and test files  
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 600 TE_Fax TestTransmitFax06
END_TESTCASE TEL-FAX-NA-0010

