// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// TE_Fax_setup.script
// 
//

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_Test.FAX c:\Test.FAX
RUN_UTILS MakeReadWrite c:\Test.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_One.FAX c:\One.FAX
RUN_UTILS MakeReadWrite c:\One.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_Two.FAX c:\Two.FAX
RUN_UTILS MakeReadWrite c:\Two.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_Six.FAX c:\Six.FAX
RUN_UTILS MakeReadWrite c:\Six.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_Blank.FAX c:\Blank.FAX
RUN_UTILS MakeReadWrite c:\Blank.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_BadPage.FAX c:\BadPage.FAX
RUN_UTILS MakeReadWrite c:\BadPage.FAX

RUN_UTILS CopyFile z:\TestData\Data\TE_Fax_Chart4.FAX c:\Chart4.FAX
RUN_UTILS MakeReadWrite c:\Chart4.FAX

ced -i z:\TestData\configs\TE_Fax_9210_comm1.cfg ced.log
