//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-EAP-EO-0001
//!@SYMTestCaseID BA-CTSY-EAP-EO-0001
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobileSmartCardEap::Open
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobileSmartCardEap::Open
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyEAPAuthenticationFU.TestOpen0001L
END_TESTCASE BA-CTSY-EAP-EO-0001
