//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE te_ctsy_component

START_TESTCASE BA-CTSY-NTWC-RMPDNS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-RMPDNS-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStartV20001L
END_TESTCASE BA-CTSY-NTWC-RMPDNS-0001

START_TESTCASE BA-CTSY-NTWC-RMPDNS-0002
//!@SYMTestCaseID BA-CTSY-NTWC-RMPDNS-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStartV20002L
END_TESTCASE BA-CTSY-NTWC-RMPDNS-0002

START_TESTCASE BA-CTSY-NTWC-RMPDNS-0004
//!@SYMTestCaseID BA-CTSY-NTWC-RMPDNS-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to CRetrieveMobilePhoneDetectedNetworks::StartV2
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStartV20004L
END_TESTCASE BA-CTSY-NTWC-RMPDNS-0004
	
START_TESTCASE BA-CTSY-NTWC-EMPDNS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-EMPDNS-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneDetectedNetworks::Start
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneDetectedNetworks::Start
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStart0001L
END_TESTCASE BA-CTSY-NTWC-EMPDNS-0001

START_TESTCASE BA-CTSY-NTWC-RMPDNS5-0001
//!@SYMTestCaseID BA-CTSY-NTWC-RMPDNS5-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for CRetrieveMobilePhoneDetectedNetworks::StartV5
//!@SYMTestPriority High
//!@SYMTestActions Invokes CRetrieveMobilePhoneDetectedNetworks::StartV5
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStartV50001L
END_TESTCASE BA-CTSY-NTWC-RMPDNS5-0001

START_TESTCASE BA-CTSY-NTWC-MGNI-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGNI-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNITZInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNITZInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNITZInfo0001L
END_TESTCASE BA-CTSY-NTWC-MGNI-0001

START_TESTCASE BA-CTSY-NTWC-MGNI-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGNI-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNITZInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNITZInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNITZInfo0003L
END_TESTCASE BA-CTSY-NTWC-MGNI-0003

START_TESTCASE BA-CTSY-NTWC-MSN-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MSN-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SelectNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SelectNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSelectNetwork0001L
END_TESTCASE BA-CTSY-NTWC-MSN-0001

START_TESTCASE BA-CTSY-NTWC-MSN-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MSN-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::SelectNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::SelectNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSelectNetwork0002L
END_TESTCASE BA-CTSY-NTWC-MSN-0002

START_TESTCASE BA-CTSY-NTWC-MSN-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MSN-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::SelectNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::SelectNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSelectNetwork0004L
END_TESTCASE BA-CTSY-NTWC-MSN-0004

START_TESTCASE BA-CTSY-NTWC-MGCM-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGCM-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentMode
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentMode
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentMode0001L
END_TESTCASE BA-CTSY-NTWC-MGCM-0001

START_TESTCASE BA-CTSY-NTWC-MGHN-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetHomeNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0001L
END_TESTCASE BA-CTSY-NTWC-MGHN-0001

START_TESTCASE BA-CTSY-NTWC-MGHN-0001a
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0001a
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetHomeNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0001aL
END_TESTCASE BA-CTSY-NTWC-MGHN-0001a

START_TESTCASE BA-CTSY-NTWC-MGHN-0001b
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0001b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetHomeNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0001bL
END_TESTCASE BA-CTSY-NTWC-MGHN-0001b

START_TESTCASE BA-CTSY-NTWC-MGHN-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetHomeNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0002L
END_TESTCASE BA-CTSY-NTWC-MGHN-0002

START_TESTCASE BA-CTSY-NTWC-MGHN-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetHomeNetwork with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetHomeNetwork with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0003L
END_TESTCASE BA-CTSY-NTWC-MGHN-0003

START_TESTCASE BA-CTSY-NTWC-MGHN-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetHomeNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0004L
END_TESTCASE BA-CTSY-NTWC-MGHN-0004

START_TESTCASE BA-CTSY-NTWC-MGHN-0004b
//!@SYMTestCaseID BA-CTSY-NTWC-MGHN-0004b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetHomeNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetHomeNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetwork0004bL
END_TESTCASE BA-CTSY-NTWC-MGHN-0004b

START_TESTCASE BA-CTSY-NTWC-MGNC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGNC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkCaps
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkCaps
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkCaps0001L
END_TESTCASE BA-CTSY-NTWC-MGNC-0001

START_TESTCASE BA-CTSY-NTWC-MNMC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNMC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyModeChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyModeChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyModeChange0001L
END_TESTCASE BA-CTSY-NTWC-MNMC-0001

START_TESTCASE BA-CTSY-NTWC-MNMC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MNMC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyModeChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyModeChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyModeChange0002L
END_TESTCASE BA-CTSY-NTWC-MNMC-0002

START_TESTCASE BA-CTSY-NTWC-MNMC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MNMC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyModeChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyModeChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyModeChange0004L
END_TESTCASE BA-CTSY-NTWC-MNMC-0004

START_TESTCASE BA-CTSY-NTWC-MGCN-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0001L
END_TESTCASE BA-CTSY-NTWC-MGCN-0001

START_TESTCASE BA-CTSY-NTWC-MGCN-0001b
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0001b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0001bL
END_TESTCASE BA-CTSY-NTWC-MGCN-0001b

START_TESTCASE BA-CTSY-NTWC-MGCN-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetCurrentNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetCurrentNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0002L
END_TESTCASE BA-CTSY-NTWC-MGCN-0002

START_TESTCASE BA-CTSY-NTWC-MGCN-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentNetwork with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentNetwork with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0003L
END_TESTCASE BA-CTSY-NTWC-MGCN-0003

START_TESTCASE BA-CTSY-NTWC-MGCN-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetCurrentNetwork
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetCurrentNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0004L
END_TESTCASE BA-CTSY-NTWC-MGCN-0004

START_TESTCASE BA-CTSY-NTWC-MGCN-0004b
//!@SYMTestCaseID BA-CTSY-NTWC-MGCN-0004b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetCurrentNetwork (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetCurrentNetwork
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetwork0004bL
END_TESTCASE BA-CTSY-NTWC-MGCN-0004b

START_TESTCASE BA-CTSY-NTWC-MNIC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNIC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyNITZInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyNITZInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNITZInfoChange0001L
END_TESTCASE BA-CTSY-NTWC-MNIC-0001

START_TESTCASE BA-CTSY-NTWC-MNIC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MNIC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyNITZInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyNITZInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNITZInfoChange0002L
END_TESTCASE BA-CTSY-NTWC-MNIC-0002

START_TESTCASE BA-CTSY-NTWC-MNIC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MNIC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyNITZInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyNITZInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNITZInfoChange0004L
END_TESTCASE BA-CTSY-NTWC-MNIC-0004

START_TESTCASE BA-CTSY-NTWC-MGCNN-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGCNN-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentNetworkName
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentNetworkName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetworkName0001L
END_TESTCASE BA-CTSY-NTWC-MGCNN-0001

START_TESTCASE BA-CTSY-NTWC-MGCNN-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGCNN-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCurrentNetworkName with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCurrentNetworkName with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetworkName0003L
END_TESTCASE BA-CTSY-NTWC-MGCNN-0003

START_TESTCASE BA-CTSY-NTWC-MGCNN-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MGCNN-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetCurrentNetworkName
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetCurrentNetworkName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCurrentNetworkName0004L
END_TESTCASE BA-CTSY-NTWC-MGCNN-0004

START_TESTCASE BA-CTSY-NTWC-MGSPN-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetServiceProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0001L
END_TESTCASE BA-CTSY-NTWC-MGSPN-0001

START_TESTCASE BA-CTSY-NTWC-MGSPN-0001a
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0001a
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test for coverage increasing
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0001aL
END_TESTCASE BA-CTSY-NTWC-MGSPN-0001a

START_TESTCASE BA-CTSY-NTWC-MGSPN-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetServiceProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetServiceProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0002L
END_TESTCASE BA-CTSY-NTWC-MGSPN-0002

START_TESTCASE BA-CTSY-NTWC-MGSPN-0002b
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0002b
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetServiceProviderName combined with a cancel request
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetServiceProviderName, cancels the first request
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0002bL
END_TESTCASE BA-CTSY-NTWC-MGSPN-0002b

START_TESTCASE BA-CTSY-NTWC-MGSPN-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetServiceProviderName with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetServiceProviderName with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0003L
END_TESTCASE BA-CTSY-NTWC-MGSPN-0003

START_TESTCASE BA-CTSY-NTWC-MGSPN-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MGSPN-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetServiceProviderName
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetServiceProviderName
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetServiceProviderName0004L
END_TESTCASE BA-CTSY-NTWC-MGSPN-0004

START_TESTCASE BA-CTSY-NTWC-MNISS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNISS-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkInvScanSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkInvScanSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkInvScanSetting0001L
END_TESTCASE BA-CTSY-NTWC-MNISS-0001

START_TESTCASE BA-CTSY-NTWC-MNNISE-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNNISE-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyNetworkInvScanEvent
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyNetworkInvScanEvent
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkInvScanEvent0001L
END_TESTCASE BA-CTSY-NTWC-MNNISE-0001

START_TESTCASE BA-CTSY-NTWC-MGHNSP-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGHNSP-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetHomeNetworkSearchPeriod
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetHomeNetworkSearchPeriod
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetHomeNetworkSearchPeriod0001L
END_TESTCASE BA-CTSY-NTWC-MGHNSP-0001

START_TESTCASE BA-CTSY-NTWC-MGNSS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGNSS-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkSelectionSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkSelectionSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkSelectionSetting0001L
END_TESTCASE BA-CTSY-NTWC-MGNSS-0001

START_TESTCASE BA-CTSY-NTWC-MGNSS-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MGNSS-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkSelectionSetting with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkSelectionSetting with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkSelectionSetting0003L
END_TESTCASE BA-CTSY-NTWC-MGNSS-0003

START_TESTCASE BA-CTSY-NTWC-MNCNC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0001L
END_TESTCASE BA-CTSY-NTWC-MNCNC-0001

START_TESTCASE BA-CTSY-NTWC-MNCNC-0001b
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0001b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyCurrentNetworkChange (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0001bL
END_TESTCASE BA-CTSY-NTWC-MNCNC-0001b

START_TESTCASE BA-CTSY-NTWC-MNCNC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0002L
END_TESTCASE BA-CTSY-NTWC-MNCNC-0002

START_TESTCASE BA-CTSY-NTWC-MNCNC-0002b
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0002b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyCurrentNetworkChange (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0002bL
END_TESTCASE BA-CTSY-NTWC-MNCNC-0002b

START_TESTCASE BA-CTSY-NTWC-MNCNC-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyCurrentNetworkChange with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyCurrentNetworkChange with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0003L
END_TESTCASE BA-CTSY-NTWC-MNCNC-0003

START_TESTCASE BA-CTSY-NTWC-MNCNC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0004L
END_TESTCASE BA-CTSY-NTWC-MNCNC-0004

START_TESTCASE BA-CTSY-NTWC-MNCNC-0004b
//!@SYMTestCaseID BA-CTSY-NTWC-MNCNC-0004b
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyCurrentNetworkChange (TMobilePhoneNetworkInfoV8)
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyCurrentNetworkChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCurrentNetworkChange0004bL
END_TESTCASE BA-CTSY-NTWC-MNCNC-0004b

START_TESTCASE BA-CTSY-NTWC-MNNISC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNNISC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyNetworkInvScanChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyNetworkInvScanChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkInvScanChange0001L
END_TESTCASE BA-CTSY-NTWC-MNNISC-0001

START_TESTCASE BA-CTSY-NTWC-MSNSS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MSNSS-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSetNetworkSelectionSetting0001L
END_TESTCASE BA-CTSY-NTWC-MSNSS-0001

START_TESTCASE BA-CTSY-NTWC-MSNSS-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MSNSS-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSetNetworkSelectionSetting0002L
END_TESTCASE BA-CTSY-NTWC-MSNSS-0002

START_TESTCASE BA-CTSY-NTWC-MSNSS-0003
//!@SYMTestCaseID BA-CTSY-NTWC-MSNSS-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::SetNetworkSelectionSetting with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::SetNetworkSelectionSetting with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSetNetworkSelectionSetting0003L
END_TESTCASE BA-CTSY-NTWC-MSNSS-0003

START_TESTCASE BA-CTSY-NTWC-MSNSS-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MSNSS-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::SetNetworkSelectionSetting
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestSetNetworkSelectionSetting0004L
END_TESTCASE BA-CTSY-NTWC-MSNSS-0004

START_TESTCASE BA-CTSY-NTWC-MGLUAT-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGLUAT-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetLastUsedAccessTechnology
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetLastUsedAccessTechnology
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetLastUsedAccessTechnology0001L
END_TESTCASE BA-CTSY-NTWC-MGLUAT-0001

START_TESTCASE BA-CTSY-NTWC-MSPNL-0001
//!@SYMTestCaseID          BA-CTSY-NTWC-MSPNL-0001
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for RMobilePhone::StorePreferredNetworksListL
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::StorePreferredNetworksListL with a list of Preferred Networks.
//!@SYMTestExpectedResults LTSY receives the same list of Preferred Networks. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStorePreferredNetworksListL0001L
END_TESTCASE BA-CTSY-NTWC-MSPNL-0001

START_TESTCASE BA-CTSY-NTWC-MSPNL-0001a
//!@SYMTestCaseID          BA-CTSY-NTWC-MSPNL-0001a
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for RMobilePhone::StorePreferredNetworksListL with empty list
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::StorePreferredNetworksListL with an empty list of Preferred Networks.
//!@SYMTestExpectedResults LTSY receives an empty list of Preferred Networks.
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStorePreferredNetworksListL0001aL
END_TESTCASE BA-CTSY-NTWC-MSPNL-0001a

START_TESTCASE BA-CTSY-NTWC-MSPNL-0001b
//!@SYMTestCaseID          BA-CTSY-NTWC-MSPNL-0001b
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for RMobilePhone::StorePreferredNetworksListL
//!@   			   with error and with duplicate LTSY complete message
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::StorePreferredNetworksListL.
//!                        2. LTSY returns error.  
//!                        3. Test code receives error.
//!                        3. Invoke RMobilePhone:StorePreferredNetworksListL.
//!                        4. LTSY returns duplicate complete message with KErrNone
//!                        5. Duplicate complete message is ignored and test code receives KErrNone.  
//!@SYMTestExpectedResults All tests pass. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStorePreferredNetworksListL0001bL
END_TESTCASE BA-CTSY-NTWC-MSPNL-0001b

START_TESTCASE BA-CTSY-NTWC-MSPNL-0002
//!@SYMTestCaseID          BA-CTSY-NTWC-MSPNL-0002
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for Cancelling RMobilePhone::StorePreferredNetworksListL
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::StorePreferredNetworksListL.
//!                        2. Cancel the outstanding request.
//!                        3. LTSY ignores cancelling the request and stores the preferred networks list.
//!@SYMTestExpectedResults Request status of the operation is KErrNone. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStorePreferredNetworksListL0002L
END_TESTCASE BA-CTSY-NTWC-MSPNL-0002

START_TESTCASE BA-CTSY-NTWC-MSPNL-0004
//!@SYMTestCaseID          BA-CTSY-NTWC-MSPNL-0004
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for multiple client requests to RMobilePhone::StorePreferredNetworksListL
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::StorePreferredNetworksListL.
//!                        2. Invoke RMobilePhone::StorePreferredNetworksListL from second client.
//!@SYMTestExpectedResults Second cleint receives KErrServerBusy. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestStorePreferredNetworksListL0004L
END_TESTCASE BA-CTSY-NTWC-MSPNL-0004

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0001
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0001
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for CRetrieveMobilePhonePreferredNetworks::Start
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. Add a new entry to the list.
//!                        3. Invoke RMobilePhone::StorePreferredNetworksListL. 
//!@SYMTestExpectedResults LTSY receives the modified list and test code receives KErrNone. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0001L
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0001

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0001a
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0001a
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for CRetrieveMobilePhonePreferredNetworks::Start
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. Remove an entry from the list.
//!                        3. Invoke RMobilePhone::StorePreferredNetworksListL. 
//!@SYMTestExpectedResults LTSY receives the modified list and test code receives KErrNone. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0001aL
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0001a

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0001b
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0001b
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for CRetrieveMobilePhonePreferredNetworks::Start with empty list
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. LTSY returns an empty list of preferred networks.
//!@SYMTestExpectedResults Test code receives an empty list of preferred networks. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0001bL
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0001b

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0001c
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0001c
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for CRetrieveMobilePhonePreferredNetworks::Start with error
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. LTSY returns error.
//!@SYMTestExpectedResults Test code receives error. 
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0001cL
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0001c

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0002
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0002
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for Cancelling CRetrieveMobilePhonePreferredNetworks::Start
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. Cancel outstanding request.
//!@SYMTestExpectedResults Request status of the operation is KErrCancel
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0002L
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0002

START_TESTCASE BA-CTSY-NTWC-CRMPPN-0004
//!@SYMTestCaseID          BA-CTSY-NTWC-CRMPPN-0004
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for multiple client requests to CRetrieveMobilePhonePreferredNetworks::Start
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke CRetrieveMobilePhonePreferredNetworks::Start.
//!                        2. Invoke CRetrieveMobilePhonePreferredNetworks::Start from second client.
//!@SYMTestExpectedResults Second client receives KErrInUse.
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestRetrieveMobilePhonePreferredNetworks0004L
END_TESTCASE BA-CTSY-NTWC-CRMPPN-0004

START_TESTCASE BA-CTSY-NTWC-MGNRS-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MGNRS-0001
//!@SYMPREQ 1551
//!@SYMCR 1595
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkRegistrationStatus0001L
END_TESTCASE BA-CTSY-NTWC-MGNRS-0001

START_TESTCASE BA-CTSY-NTWC-MGNRS-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MGNRS-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkRegistrationStatus0002L
END_TESTCASE BA-CTSY-NTWC-MGNRS-0002

START_TESTCASE BA-CTSY-NTWC-MGNRS-0004                                  
//!@SYMTestCaseID BA-CTSY-NTWC-MGNRS-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetNetworkRegistrationStatus
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetNetworkRegistrationStatus0004L
END_TESTCASE BA-CTSY-NTWC-MGNRS-0004

START_TESTCASE BA-CTSY-NTWC-MNPNLC-0001
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for RMobilePhone::NotifyPreferredNetworksListChange
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::NotifyPreferredNetworksListChange.
//!                        2. Invoke RMobilePhone::StorePreferredNetworksListL.
//!@SYMTestExpectedResults Test code receives preferred network list notification
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyPreferredNetworksListChange0001L
END_TESTCASE BA-CTSY-NTWC-MNPNLC-0001

START_TESTCASE BA-CTSY-NTWC-MNPNLC-0002
//!@SYMTestCaseID          BA-CTSY-NTWC-MNPNLC-0002
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for Cancelling RMobilePhone::NotifyPreferredNetworksListChange
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::NotifyPreferredNetworksListChange.
//!                        2. Cancel subscription to preferred network list change.
//!                        3. Invoke RMobilePhone::StorePreferredNetworksListL.
//!@SYMTestExpectedResults Test code does not receive preferred network list notification
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyPreferredNetworksListChange0002L
END_TESTCASE BA-CTSY-NTWC-MNPNLC-0002

START_TESTCASE BA-CTSY-NTWC-MNPNLC-0004
//!@SYMPREQ                417-71654
//!@SYMComponent           telephony_ctsy
//!@SYMTestCaseDesc        Test support in CTSY for multiple client requests to RMobilePhone::NotifyPreferredNetworksListChange
//!@SYMTestPriority        High
//!@SYMTestActions         1. Invoke RMobilePhone::NotifyPreferredNetworksListChange.
//!                        1. Invoke RMobilePhone::NotifyPreferredNetworksListChange from second client.
//!                        2. Invoke RMobilePhone::StorePreferredNetworksListL.
//!@SYMTestExpectedResults Clients receive preferred network list notification
//!@SYMTestType            CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyPreferredNetworksListChange0004L
END_TESTCASE BA-CTSY-NTWC-MNPNLC-0004

START_TESTCASE BA-CTSY-NTWC-MNNSSC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNNSSC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkSelectionSettingChange0001L
END_TESTCASE BA-CTSY-NTWC-MNNSSC-0001

START_TESTCASE BA-CTSY-NTWC-MNNSSC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MNNSSC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkSelectionSettingChange0002L
END_TESTCASE BA-CTSY-NTWC-MNNSSC-0002

START_TESTCASE BA-CTSY-NTWC-MNNSSC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MNNSSC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyNetworkSelectionSettingChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkSelectionSettingChange0004L
END_TESTCASE BA-CTSY-NTWC-MNNSSC-0004

START_TESTCASE BA-CTSY-NTWC-MNNRSC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-MNNRSC-0001
//!@SYMPREQ 1551
//!@SYMCR 1595
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkRegistrationStatusChange0001L
END_TESTCASE BA-CTSY-NTWC-MNNRSC-0001

START_TESTCASE BA-CTSY-NTWC-MNNRSC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-MNNRSC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkRegistrationStatusChange0002L
END_TESTCASE BA-CTSY-NTWC-MNNRSC-0002

START_TESTCASE BA-CTSY-NTWC-MNNRSC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-MNNRSC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyNetworkRegistrationStatusChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyNetworkRegistrationStatusChange0004L
END_TESTCASE BA-CTSY-NTWC-MNNRSC-0004


START_TESTCASE BA-CTSY-NTWC-PGCI-0001
//!@SYMTestCaseID BA-CTSY-NTWC-PGCI-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCellInfo0001L
END_TESTCASE BA-CTSY-NTWC-PGCI-0001

START_TESTCASE BA-CTSY-NTWC-PGCI-0002
//!@SYMTestCaseID BA-CTSY-NTWC-PGCI-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCellInfo0002L
END_TESTCASE BA-CTSY-NTWC-PGCI-0002

START_TESTCASE BA-CTSY-NTWC-PGCI-0003
//!@SYMTestCaseID BA-CTSY-NTWC-PGCI-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::GetCellInfo with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::GetCellInfo with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCellInfo0003L
END_TESTCASE BA-CTSY-NTWC-PGCI-0003

START_TESTCASE BA-CTSY-NTWC-PGCI-0004
//!@SYMTestCaseID BA-CTSY-NTWC-PGCI-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::GetCellInfo
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::GetCellInfo
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestGetCellInfo0004L
END_TESTCASE BA-CTSY-NTWC-PGCI-0004

START_TESTCASE BA-CTSY-NTWC-PNCIC-0001
//!@SYMTestCaseID BA-CTSY-NTWC-PNCIC-0001
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCellInfoChange0001L
END_TESTCASE BA-CTSY-NTWC-PNCIC-0001

START_TESTCASE BA-CTSY-NTWC-PNCIC-0002
//!@SYMTestCaseID BA-CTSY-NTWC-PNCIC-0002
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for cancelling of RMobilePhone::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes cancelling of RMobilePhone::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCellInfoChange0002L
END_TESTCASE BA-CTSY-NTWC-PNCIC-0002

START_TESTCASE BA-CTSY-NTWC-PNCIC-0003
//!@SYMTestCaseID BA-CTSY-NTWC-PNCIC-0003
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for RMobilePhone::NotifyCellInfoChange with bad parameter data
//!@SYMTestPriority High
//!@SYMTestActions Invokes RMobilePhone::NotifyCellInfoChange with bad parameter data
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCellInfoChange0003L
END_TESTCASE BA-CTSY-NTWC-PNCIC-0003

START_TESTCASE BA-CTSY-NTWC-PNCIC-0004
//!@SYMTestCaseID BA-CTSY-NTWC-PNCIC-0004
//!@SYMPREQ 1551
//!@SYMComponent telephony_ctsy
//!@SYMTestCaseDesc Test support in CTSY for multiple client requests to RMobilePhone::NotifyCellInfoChange
//!@SYMTestPriority High
//!@SYMTestActions Invokes multiple client requests to RMobilePhone::NotifyCellInfoChange
//!@SYMTestExpectedResults Pass
//!@SYMTestType CT
RUN_TEST_STEP 100 te_ctsy_component TEFUnit.CCTsyNetworkControlFU.TestNotifyCellInfoChange0004L
END_TESTCASE BA-CTSY-NTWC-PNCIC-0004

