// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// UmtsGprsScpr Config 3 component integration tests.
// /////////CONFIGURATION 3 TEST CASES///////////////////
//

//! @file 


PRINT Run all Configuration 3 Test Cases

CED -i z:\testdata\configs\te_UmtsGprsScprNoSpud.xml ced.log


START_TESTCASE			NET-UMTS-UmtsGprsSCPR-0801
//! @SYMTestCaseID		NET-UMTS-UmtsGprsSCPR-0801
//! @SYMTestCaseDesc Set qos on Primary without the presense of SPUD
//! @SYMFssID
//! @SYMTestActions Setparameters on the Rsubconnection in EAttachToDefault mode.
//! @SYMTestExpectedResults Setparameters fails with KErrNotSupported.
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType CIT
RUN_SCRIPT Z:\TestData\Scripts\te_UmtsGprsScprConfig3Case1.script
END_TESTCASE			NET-UMTS-UmtsGprsSCPR-0801

RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  MakeReadWrite c:\qospolicies.ini
RUN_UTILS  MakeReadWrite c:\private\101F7989\esock\qospolicies.ini
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  DeleteFile c:\loopback.ini
RUN_UTILS  DeleteFile c:\qospolicies.ini
RUN_UTILS  DeleteFile c:\private\101F7989\esock\qospolicies.ini


PRINT Complete_TEST_CASE_ID_PLACEHOLDER_Tests

