//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
// backup the old commsdb

RUN_UTILS  MkDir c:\simtsy\
RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt

LOAD_SUITE TE_PPPSize -SharedData
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced -i z:\testdata\configs\te_pppsize_spud.xml te_pppsize_spud.log
run_script z:\TestData\scripts\te_esock_test_loadesock.script

RUN_UTILS  CopyFile z:\TestData\Configs\TE_PPPSize_config.txt c:\simtsy\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\TE_PPPSize_config.txt c:\config.txt

START_TESTCASE          NET-Spud-NetworkSide-0701
//! @SYMTestCaseID      NET-Spud-NetworkSide-0701
RUN_TEST_STEP 2000 TE_PPPSize PPPMinMaxMMU z:\testdata\configs\te_pppsize_spud.ini
END_TESTCASE            NET-Spud-NetworkSide-0701

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt

