//
// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  MkDir c:\simtsy\
RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  MakeReadWrite c:\loopback.ini
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  DeleteFile c:\loopback.ini

RUN_UTILS  CopyFile z:\TestData\Configs\te_spudnetworkside_mbufexhaustion_config.txt c:\simtsy\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\te_spudnetworkside_mbufexhaustion_config.txt c:\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\te_spudnetworkside_mbufexhaustion_loopbackCSY.ini c:\loopback.ini

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced -i z:\testdata\configs\te_spudnetworkside_mbufexhaustion.cfg
run_script z:\TestData\scripts\te_esock_test_loadesock.script

LOAD_SUITE TE_SpudNetworkSide

START_TESTCASE          CBS-RAWIP-0002
//! @SYMTestCaseID      CBS-RAWIP-0002
//! @SYMTestCaseDesc Checks that the PDP flow is robust when MBufs are exhausted.
//! @SYMTestActions Connect 2 sockets using loopback, PDP flow receives a packet when MBufs are exhausted, PDP flow subsequently receives a packet when MBufs available.  
//! @SYMTestExpectedResults  No packet received when MBufs are exhausted, packet received when MBufs available.
//! @SYMTestPriority Critical
//! @SYMTestStatus Implemented
//! @SYMTestType CIT
RUN_TEST_STEP 2000 TE_SpudNetworkSide CRawIpMBufExhaustionRx z:\testdata\configs\te_spudnetworkside_mbufexhaust.ini MBufExhaustionRx
END_TESTCASE            CBS-RAWIP-0002

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

RUN_UTILS  MakeReadWrite c:\simtsy\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
RUN_UTILS  MakeReadWrite c:\loopback.ini
RUN_UTILS  DeleteFile c:\simtsy\config.txt
RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  DeleteFile c:\loopback.ini
